### ISSUE TITLE
Helium top bar shows "unresolved internal reference" for RST files

### ISSUE THREAD

**Issue by Ostrzyciel** [planet42/Laika#320] opened 2022-08-24 18:12 UTC
Library version: 0.18.2

When I use the library API to process an RST file, in the top bar of the Helium template I get the following error instead of the "Home" button:
![image](https://user-images.githubusercontent.com/56843159/186492101-e7854c9a-dc64-4db9-9e40-ec563c6bddd5.png)

Used RST file for reference:
<details>
  <summary>README.rst</summary>

```
***************
Introduction
***************

AAAA.
```
</details>

**Comment by jenshalm** [comment] 2022-08-25 00:34
That's a duplicate of the discussion in #309 - it's expected behaviour, the only problem is that in this particular case the error message does not point to the actual underlying cause, which I hope to improve in a future release.

For different ways to avoid the error see the linked discussion. You can also use a custom default template to remove the home link entirely if you don't need it.

**Closed by jenshalm** 2022-08-25 00:34 UTC
Labels: duplicate

**Comment by jenshalm** [comment] 2022-08-25 00:36
For further questions or feedback about this issue, please use #309, thanks!
